// PRISMA ERROR CODE EXCEPTION
export const UNIQUE_CONSTRAINT_FAILED = 'P2002';
export const FOREIGN_KEY_CONSTRAINT = 'P2003';
export const RECORD_TO_DELETE_DOES_NOT_EXIST = 'P2025';
export const NULL_CONSTRAINT_VIOLATION = 'P2011';

// QUEUE RABBITMQ
export const RABBIT_PATTERN_LOCALIDADE_CREATED = 'localidade_created';
export const QUEUE_LOCALIDADE = 'localidade_queue';

// CONTROLERS PAGINATION
export const LIMIT_DEFAULT = 50;
export const PAGE_DEFAULT = 1;
