export enum Sexo {
  MASCULINO = 'MASCULINO',
  FEMININO = 'FEMININO',
}

export enum Role {
  ADMIN = 'ADMIN',
  CATEQUISTA_NACIONAL = 'CATEQUISTA_NACIONAL',
  CATEQUISTA_GRANDE_REGIAO = 'CATEQUISTA_GRANDE_REGIAO',
  CATEQUISTA_REGIAO = 'CATEQUISTA_REGIAO',
  CATEQUISTA_SETOR = 'CATEQUISTA_SETOR',
  CATEQUISTA_PAROQUIA = 'CATEQUISTA_PAROQUIA',
  SECRETARIA_CNC = 'SECRETARIA_CNC',
  SECRETARIA_PAROQUIA = 'SECRETARIA_PAROQUIA',
}
