-- CreateEnum
CREATE TYPE "roles" AS ENUM ('ADMIN', 'CATEQUISTA_NACIONAL', 'CATEQUISTA_GRANDE_REGIAO', 'CATEQUISTA_REGIAO', 'CATEQUISTA_SETOR', 'CATEQUISTA_PAROQUIA', 'SECRETARIA_CNC', 'SECRETARIA_PAROQUIA');

-- AlterTable
ALTER TABLE "endereco" ALTER COLUMN "pais" SET DATA TYPE VARCHAR(50);

-- CreateTable
CREATE TABLE "user" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "role" "roles" NOT NULL DEFAULT 'SECRETARIA_PAROQUIA',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "user_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "user_email_key" ON "user"("email");
